# Google Cloud Build configuration for Stockmeter
# This file defines the CI/CD pipeline for building and deploying the application

substitutions:
  _REGION: us-central1
  _BACKEND_SERVICE_NAME: stockmeter-backend
  _FRONTEND_SERVICE_NAME: stockmeter-frontend
  _ARTIFACT_REGISTRY: us-central1-docker.pkg.dev/${PROJECT_ID}/stockmeter

steps:
  # Step 1: Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/backend:${SHORT_SHA}'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - './backend'
    waitFor: ['-']

  # Step 2: Build frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/frontend:${SHORT_SHA}'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/frontend:latest'
      - '-f'
      - 'frontend/Dockerfile'
      - './frontend'
    waitFor: ['-']

  # Step 3: Push backend image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - '--all-tags'
      - '${_ARTIFACT_REGISTRY}/backend'
    waitFor: ['build-backend']

  # Step 4: Push frontend image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - '--all-tags'
      - '${_ARTIFACT_REGISTRY}/frontend'
    waitFor: ['build-frontend']

  # Step 5: Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_BACKEND_SERVICE_NAME}'
      - '--image'
      - '${_ARTIFACT_REGISTRY}/backend:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3001'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60s'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--add-cloudsql-instances'
      - '${PROJECT_ID}:${_REGION}:stockmeter-db'
      - '--vpc-connector'
      - 'stockmeter-connector'
    waitFor: ['push-backend']

  # Step 6: Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_FRONTEND_SERVICE_NAME}'
      - '--image'
      - '${_ARTIFACT_REGISTRY}/frontend:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60s'
      - '--set-env-vars'
      - 'NODE_ENV=production'
    waitFor: ['push-frontend']

# Images to be pushed to Artifact Registry
images:
  - '${_ARTIFACT_REGISTRY}/backend:${SHORT_SHA}'
  - '${_ARTIFACT_REGISTRY}/backend:latest'
  - '${_ARTIFACT_REGISTRY}/frontend:${SHORT_SHA}'
  - '${_ARTIFACT_REGISTRY}/frontend:latest'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Build timeout (20 minutes)
timeout: 1200s
